// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/validation-controller/internal/handler (interfaces: ValidationHandlerInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_validation.go -package=mocks github.com/validation-controller/internal/handler ValidationHandlerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	reconciler "github.com/validation-controller/internal/utils/reconciler"
	gomock "go.uber.org/mock/gomock"
)

// MockValidationHandlerInterface is a mock of ValidationHandlerInterface interface.
type MockValidationHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidationHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockValidationHandlerInterfaceMockRecorder is the mock recorder for MockValidationHandlerInterface.
type MockValidationHandlerInterfaceMockRecorder struct {
	mock *MockValidationHandlerInterface
}

// NewMockValidationHandlerInterface creates a new mock instance.
func NewMockValidationHandlerInterface(ctrl *gomock.Controller) *MockValidationHandlerInterface {
	mock := &MockValidationHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockValidationHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationHandlerInterface) EXPECT() *MockValidationHandlerInterfaceMockRecorder {
	return m.recorder
}

// CheckPodStatus mocks base method.
func (m *MockValidationHandlerInterface) CheckPodStatus(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPodStatus", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPodStatus indicates an expected call of CheckPodStatus.
func (mr *MockValidationHandlerInterfaceMockRecorder) CheckPodStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPodStatus", reflect.TypeOf((*MockValidationHandlerInterface)(nil).CheckPodStatus), ctx)
}

// CleanupExpiredPod mocks base method.
func (m *MockValidationHandlerInterface) CleanupExpiredPod(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredPod", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredPod indicates an expected call of CleanupExpiredPod.
func (mr *MockValidationHandlerInterfaceMockRecorder) CleanupExpiredPod(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredPod", reflect.TypeOf((*MockValidationHandlerInterface)(nil).CleanupExpiredPod), ctx)
}

// EnsureInitialized mocks base method.
func (m *MockValidationHandlerInterface) EnsureInitialized(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureInitialized", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureInitialized indicates an expected call of EnsureInitialized.
func (mr *MockValidationHandlerInterfaceMockRecorder) EnsureInitialized(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureInitialized", reflect.TypeOf((*MockValidationHandlerInterface)(nil).EnsureInitialized), ctx)
}

// EnsurePodExists mocks base method.
func (m *MockValidationHandlerInterface) EnsurePodExists(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePodExists", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsurePodExists indicates an expected call of EnsurePodExists.
func (mr *MockValidationHandlerInterfaceMockRecorder) EnsurePodExists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePodExists", reflect.TypeOf((*MockValidationHandlerInterface)(nil).EnsurePodExists), ctx)
}

// EnsureSpecCurrent mocks base method.
func (m *MockValidationHandlerInterface) EnsureSpecCurrent(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSpecCurrent", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureSpecCurrent indicates an expected call of EnsureSpecCurrent.
func (mr *MockValidationHandlerInterfaceMockRecorder) EnsureSpecCurrent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSpecCurrent", reflect.TypeOf((*MockValidationHandlerInterface)(nil).EnsureSpecCurrent), ctx)
}

// HandleRetry mocks base method.
func (m *MockValidationHandlerInterface) HandleRetry(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRetry", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRetry indicates an expected call of HandleRetry.
func (mr *MockValidationHandlerInterfaceMockRecorder) HandleRetry(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRetry", reflect.TypeOf((*MockValidationHandlerInterface)(nil).HandleRetry), ctx)
}

// UpdatePhase mocks base method.
func (m *MockValidationHandlerInterface) UpdatePhase(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhase", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePhase indicates an expected call of UpdatePhase.
func (mr *MockValidationHandlerInterfaceMockRecorder) UpdatePhase(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhase", reflect.TypeOf((*MockValidationHandlerInterface)(nil).UpdatePhase), ctx)
}
