# permissions for end users to admin Validation resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: validation-controller
    app.kubernetes.io/managed-by: kustomize
  name: validation-admin-role
rules:
- apiGroups:
  - validation.devinfra.io
  resources:
  - validations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.devinfra.io
  resources:
  - validations/status
  verbs:
  - get
